"use client";

import { useEffect, useMemo, useState } from "react";
import { AppFrame, PageTitle } from "../components/AppFrame";
import { useNovaStore } from "../components/nova-store";

function AnimatedValue({value,format=(item)=>String(item)}:{value:number;format?:(item:number)=>string}){
  const [display,setDisplay]=useState(0);
  useEffect(()=>{let frame=0;const started=performance.now(),duration=850;const tick=(time:number)=>{const progress=Math.min(1,(time-started)/duration),eased=1-Math.pow(1-progress,3);setDisplay(Math.round(value*eased));if(progress<1)frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[value]);
  return <>{format(display)}</>;
}

export default function AnalyticsPage(){
  const {data}=useNovaStore();const [days,setDays]=useState(14);const [projectId,setProjectId]=useState("all");const now=Date.now(),start=now-days*86400000,previousStart=start-days*86400000;
  const sessions=useMemo(()=>data.sessions.filter(item=>item.startedAt>=start&&(projectId==="all"||item.projectId===projectId)),[data.sessions,start,projectId]);const previous=data.sessions.filter(item=>item.startedAt>=previousStart&&item.startedAt<start&&(projectId==="all"||item.projectId===projectId));
  const total=Math.round(sessions.reduce((sum,item)=>sum+item.durationSeconds,0)/60),previousTotal=Math.round(previous.reduce((sum,item)=>sum+item.durationSeconds,0)/60),change=previousTotal?Math.round((total-previousTotal)/previousTotal*100):total?100:0;
  const chart=Array.from({length:days},(_,offset)=>{const day=new Date();day.setHours(0,0,0,0);day.setDate(day.getDate()-(days-1-offset));const end=day.getTime()+86400000;return{label:day.getDate(),minutes:Math.round(sessions.filter(item=>item.startedAt>=day.getTime()&&item.startedAt<end).reduce((sum,item)=>sum+item.durationSeconds,0)/60)}});const max=Math.max(60,...chart.map(item=>item.minutes));
  const longest=Math.round(Math.max(0,...sessions.map(item=>item.durationSeconds))/60);const early=sessions.filter(item=>new Date(item.startedAt).getHours()<10).length;const bestDay=chart.reduce((best,item)=>item.minutes>best.minutes?item:best,{label:0,minutes:0});
  const exportCsv=()=>{const rows=["date,project,duration_minutes",...sessions.map(item=>`${new Date(item.startedAt).toISOString()},${data.projects.find(project=>project.id===item.projectId)?.name??"Focus"},${Math.round(item.durationSeconds/60)}`)];const blob=new Blob([rows.join("\n")],{type:"text/csv"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="nova-analytics.csv";link.click();URL.revokeObjectURL(link.href)};
  return <AppFrame active="analytics"><PageTitle eyebrow="Тільки реальні дані" title="Аналітика фокусу" description="Фільтруй власні сесії, порівнюй періоди та знаходь персональні рекорди." action={<div className="analytics-filters"><select value={days} onChange={event=>setDays(Number(event.target.value))}><option value="7">7 днів</option><option value="14">14 днів</option><option value="30">30 днів</option><option value="90">90 днів</option></select><select value={projectId} onChange={event=>setProjectId(event.target.value)}><option value="all">Усі проєкти</option>{data.projects.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select><button onClick={exportCsv}>CSV ↓</button><button onClick={()=>window.print()}>PDF ↓</button></div>}/>
    <section className="metric-row" key={`metrics-${days}-${projectId}-${total}`}><div><span>Фокус за період</span><strong><AnimatedValue value={total} format={value=>`${Math.floor(value/60)}г ${value%60}хв`}/></strong><small className={change>=0?"positive":"negative"}>{change>=0?"↑":"↓"} {Math.abs(change)}% проти попереднього</small></div><div><span>Середня сесія</span><strong><AnimatedValue value={sessions.length?Math.round(total/sessions.length):0} format={value=>`${value} хв`}/></strong><small>{sessions.length} реальних сесій</small></div><div><span>Найдовша сесія</span><strong><AnimatedValue value={longest} format={value=>`${value} хв`}/></strong><small>Персональний рекорд</small></div><div><span>Ранній фокус</span><strong><AnimatedValue value={early}/></strong><small>сесій до 10:00</small></div></section>
    <section className="analytics-main"><div className="big-chart"><div className="panel-heading"><div><span className="eyebrow">Динаміка</span><h2>Хвилини у фокусі</h2></div><span className="trend">{change>=0?"+":""}{change}%</span></div><div className="fourteen-chart" key={`chart-${days}-${projectId}-${total}`}>{chart.map((day,index)=><div key={index}><span>{day.minutes||""}</span><i style={{height:`${Math.max(3,day.minutes/max*100)}%`}}/><small>{day.label}</small></div>)}</div></div><div className="focus-score"><span className="eyebrow">Рекорд періоду</span><div className="score-ring" key={`ring-${days}-${projectId}-${bestDay.minutes}`} aria-label={`Рекорд: ${bestDay.minutes} хвилин`} style={{"--score-target":`${Math.min(360,bestDay.minutes/Math.max(90,bestDay.minutes)*360)}deg`} as React.CSSProperties}><div className="score-ring-value"><strong><AnimatedValue value={bestDay.minutes}/></strong><small>хв</small></div></div><h2>{bestDay.minutes?`${bestDay.label}-го числа`:"Ще попереду"}</h2><p>{bestDay.minutes?"Найсильніший день у вибраному періоді.":"Заверши першу сесію, щоб побачити рекорди."}</p></div></section>
    <section className="analytics-lower"><div className="category-panel"><span className="eyebrow">Розподіл</span><h2>Увага за проєктами</h2>{data.projects.map(project=>{const minutes=Math.round(sessions.filter(item=>item.projectId===project.id).reduce((sum,item)=>sum+item.durationSeconds,0)/60);return <div className="category-row" key={`${project.id}-${days}-${projectId}`}><i style={{background:project.color}}/><span>{project.name}</span><div><b style={{width:`${total?minutes/total*100:0}%`,background:project.color}}/></div><strong>{minutes} хв</strong></div>})}</div><div className="heat-panel"><span className="eyebrow">Активність</span><h2>Теплова карта</h2><div className="heat-grid" key={`heat-${days}-${projectId}-${sessions.length}`}>{Array.from({length:35},(_,index)=>{const day=new Date();day.setDate(day.getDate()-(34-index));const count=data.sessions.filter(item=>new Date(item.startedAt).toDateString()===day.toDateString()).length;return <i key={index} className={count>1?"hot":count?"warm":""} title={`${day.toLocaleDateString("uk-UA")}: ${count} сесій`}/>})}</div><div className="heat-labels"><span>5 тижнів тому</span><span>Сьогодні</span></div></div></section>
  </AppFrame>
}
