"use client";

import { useEffect, useMemo, useState } from "react";
import { navItems } from "./AppFrame";
import { useNovaStore } from "./nova-store";

function navigateTo(href: string) {
  window.location.assign(href);
}

export function GlobalTools() {
  const {data,save,ready}=useNovaStore(); const [open,setOpen]=useState(false); const [query,setQuery]=useState(""); const [onboarding,setOnboarding]=useState(false); const [step,setStep]=useState(0); const [goal,setGoal]=useState("Робота"); const [minutes,setMinutes]=useState(25); const [project,setProject]=useState("");
  useEffect(()=>{const key=(event:KeyboardEvent)=>{const target=event.target as HTMLElement;const typing=["INPUT","TEXTAREA","SELECT"].includes(target.tagName);if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setOpen(value=>!value)} if(event.key==="Escape")setOpen(false);if(!typing&&!event.ctrlKey&&!event.metaKey){if(event.key==="/"){event.preventDefault();setOpen(true)}if(event.key.toLowerCase()==="f")navigateTo("/");if(event.key.toLowerCase()==="p")navigateTo("/projects");if(event.key.toLowerCase()==="c")navigateTo("/calendar")}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[]);
  useEffect(()=>{if(ready)setOnboarding(data.projects.length===0&&!localStorage.getItem("nova-onboarded"))},[ready,data.projects.length]);
  useEffect(()=>{if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>undefined)},[]);
  const results=useMemo(()=>{const needle=query.toLowerCase();return [...navItems.map((item)=>({label:item[2],href:item[3],meta:"Сторінка"})),...data.tasks.map((task)=>({label:task.text,href:"/projects",meta:"Задача"}))].filter(item=>item.label.toLowerCase().includes(needle)).slice(0,8)},[query,data.tasks]);
  const finish=async()=>{const timestamp=Date.now();const first={id:`project-${timestamp}`,name:project.trim()||goal,color:"#dfff00",createdAt:timestamp,updatedAt:timestamp};const next={...data,projects:[first],tasks:[],sessions:[],events:[],preferences:{...data.preferences,focusMinutes:minutes}};await save(next);localStorage.setItem("nova-onboarded","1");setOnboarding(false);navigateTo("/")};
  const quickAdd=()=>{const text=query.trim(),projectId=data.projects.find(item=>!item.archived)?.id;if(!text||!projectId)return;const stamp=Date.now();save({...data,tasks:[...data.tasks,{id:`task-${stamp}`,projectId,text,done:false,status:"todo",createdAt:stamp,updatedAt:stamp}]}).finally(()=>{setQuery("");setOpen(false);navigateTo("/projects")})};
  return <>{<button className="command-trigger" type="button" onClick={()=>setOpen(true)} aria-label="Відкрити командну панель">⌘ <span>Ctrl K</span></button>}{open&&<div className="command-backdrop" role="presentation" onMouseDown={()=>setOpen(false)}><section className="command-panel" role="dialog" aria-modal="true" aria-label="Командна панель" onMouseDown={event=>event.stopPropagation()}><div className="command-search"><span>⌕</span><input autoFocus value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"&&query.trim())quickAdd()}} placeholder="Шукати або швидко додати задачу…" aria-label="Пошук"/><kbd>ESC</kbd></div><div className="command-results"><span className="eyebrow">Швидкий перехід</span>{results.map((item,index)=><button key={`${item.href}-${index}`} type="button" onClick={()=>{setOpen(false);navigateTo(item.href)}}><i>{String(index+1).padStart(2,"0")}</i><span>{item.label}<small>{item.meta}</small></span><b>↗</b></button>)}{query.trim()&&data.projects.length>0&&<button className="quick-create" type="button" onClick={quickAdd}><i>+</i><span>Створити задачу «{query.trim()}»<small>{data.projects.find(item=>!item.archived)?.name}</small></span><b>↵</b></button>}</div><footer><span>F фокус</span><span>P проєкти</span><span>C календар</span><span>Ctrl K будь-де</span></footer></section></div>}{onboarding&&<div className="onboarding-backdrop"><section className="onboarding-card" role="dialog" aria-modal="true" aria-label="Знайомство з NOVA"><div className="onboarding-progress">{[0,1,2].map(item=><i className={item<=step?"active":""} key={item}/>)}</div>{step===0&&<><span className="onboarding-mark">N</span><span className="eyebrow">Ласкаво просимо</span><h2>Знайди свій<br/><em>ритм.</em></h2><p>NOVA допоможе зберегти увагу на тому, що справді важливо.</p><button onClick={()=>setStep(1)}>Налаштувати простір →</button></>}{step===1&&<><span className="eyebrow">Крок 1 із 2</span><h2>Що зараз<br/>найважливіше?</h2><div className="goal-options">{["Робота","Навчання","Особистий розвиток"].map(item=><button className={goal===item?"active":""} onClick={()=>setGoal(item)} key={item}>{item}</button>)}</div><label className="rhythm-select">Тривалість фокусу <strong>{minutes} хв</strong><input type="range" min="10" max="60" step="5" value={minutes} onChange={event=>setMinutes(Number(event.target.value))}/></label><button onClick={()=>setStep(2)}>Продовжити →</button></>}{step===2&&<><span className="eyebrow">Крок 2 із 2</span><h2>Назви перший<br/>проєкт.</h2><input className="project-name-input" autoFocus value={project} onChange={event=>setProject(event.target.value)} placeholder={goal}/><p>Порожній простір без демонстраційних задач — лише твої справжні цілі.</p><button onClick={finish}>Увійти в NOVA →</button></>}</section></div>}</>;
}
