"use client";

import { DragEvent, FormEvent, useState } from "react";
import { AppFrame, PageTitle } from "../components/AppFrame";
import { Project, Task, useNovaStore } from "../components/nova-store";

const colors=["#dfff00","#78d6ff","#ff7a5c","#c7a7ff","#ffd66b","#ff7fd1","#67e8b5"];
const columns:[Task["status"],string][]=[["todo","Зробити"],["doing","У роботі"],["done","Готово"]];

export default function ProjectsPage(){
  const {data,save,syncing,lastSyncedAt}=useNovaStore();const [selected,setSelected]=useState<string|null>(null);const [draft,setDraft]=useState("");const [projectName,setProjectName]=useState("");const [showArchived,setShowArchived]=useState(false);const [dragging,setDragging]=useState<string|null>(null);
  const preferred=data.projects.some(item=>item.id===data.preferences.activeProjectId)?data.preferences.activeProjectId:null;const active=selected??preferred??data.projects.find(item=>!item.archived)?.id;const project=data.projects.find(item=>item.id===active);const current=data.tasks.filter(task=>task.projectId===active);
  const commit=(projects:Project[],tasks:Task[])=>save({...data,projects,tasks});
  const addProject=(event:FormEvent)=>{event.preventDefault();const name=projectName.trim();if(!name)return;const stamp=Date.now(),item={id:`project-${stamp}`,name,color:colors[data.projects.length%colors.length],archived:false,createdAt:stamp,updatedAt:stamp};save({...data,projects:[...data.projects,item],preferences:{...data.preferences,activeProjectId:item.id}});setSelected(item.id);setProjectName("")};
  const updateProject=(patch:Partial<Project>)=>project&&commit(data.projects.map(item=>item.id===project.id?{...item,...patch,updatedAt:Date.now()}:item),data.tasks);
  const updateProjectColor=(id:string,color:string)=>commit(data.projects.map(item=>item.id===id?{...item,color,updatedAt:Date.now()}:item),data.tasks);
  const rename=()=>{if(!project)return;const name=window.prompt("Нова назва проєкту",project.name)?.trim();if(name)updateProject({name})};
  const addTask=(event:FormEvent)=>{event.preventDefault();if(!draft.trim()||!active)return;const stamp=Date.now();commit(data.projects,[...data.tasks,{id:`task-${stamp}`,projectId:active,text:draft.trim(),done:false,status:"todo",sortOrder:current.length,createdAt:stamp,updatedAt:stamp}]);setDraft("")};
  const move=(id:string,status:Task["status"])=>commit(data.projects,data.tasks.map(task=>task.id===id?{...task,status,done:status==="done",updatedAt:Date.now()}:task));
  const updateTask=(id:string,patch:Partial<Task>)=>commit(data.projects,data.tasks.map(task=>task.id===id?{...task,...patch,updatedAt:Date.now()}:task));
  const editTask=(task:Task)=>{const text=window.prompt("Редагувати задачу",task.text)?.trim();if(text)updateTask(task.id,{text})};
  const duplicateTask=(task:Task)=>{const stamp=Date.now();commit(data.projects,[...data.tasks,{...task,id:`task-${stamp}`,text:`${task.text} · копія`,done:false,status:"todo",createdAt:stamp,updatedAt:stamp}])};
  const removeTask=(id:string)=>{if(window.confirm("Видалити цю задачу?"))commit(data.projects,data.tasks.filter(item=>item.id!==id))};
  const onDrop=(event:DragEvent,status:Task["status"])=>{event.preventDefault();if(dragging)move(dragging,status);setDragging(null)};
  return <AppFrame active="projects"><PageTitle eyebrow="Робочий простір" title="Проєкти" description="Створюй, плануй дедлайни й рухай задачі між етапами." action={<span className="page-status">{syncing?"Зберігаю…":lastSyncedAt?`Збережено ${new Intl.DateTimeFormat("uk-UA",{hour:"2-digit",minute:"2-digit"}).format(lastSyncedAt)}`:"Офлайн-черга активна"}</span>}/>
    <section className="project-toolbar"><form onSubmit={addProject}><input value={projectName} onChange={event=>setProjectName(event.target.value)} placeholder="Назва нового проєкту…" aria-label="Назва нового проєкту"/><button type="submit">Створити +</button></form><label><input type="checkbox" checked={showArchived} onChange={event=>setShowArchived(event.target.checked)}/> Показати архів</label></section>
    <section className="project-overview">{data.projects.filter(item=>showArchived||!item.archived).map(item=>{const items=data.tasks.filter(task=>task.projectId===item.id),done=items.filter(task=>task.done).length;return <article key={item.id} className="project-tile-shell" style={{"--project":item.color} as React.CSSProperties}><button type="button" className={`project-tile ${active===item.id?"active":""} ${item.archived?"archived":""}`} onClick={()=>setSelected(item.id)}><i/><span className="eyebrow">{item.archived?"Архів":item.deadline?`до ${new Intl.DateTimeFormat("uk-UA",{day:"numeric",month:"short"}).format(item.deadline)}`:`${items.length} задач`}</span><h2>{item.name}</h2><div><b style={{width:`${items.length?done/items.length*100:0}%`}}/></div><small>{done} виконано · {items.length-done} у роботі</small></button><div className="tile-color-picker" aria-label={`Колір проєкту ${item.name}`}>{colors.map(color=><button type="button" key={color} className={item.color.toLowerCase()===color?"selected":""} aria-label={`Вибрати колір ${color}`} style={{background:color}} onClick={()=>updateProjectColor(item.id,color)}/>)}<label className="custom-color" title="Власний колір"><input type="color" value={item.color} aria-label={`Власний колір для ${item.name}`} onChange={event=>updateProjectColor(item.id,event.target.value)}/><span>+</span></label></div></article>})}</section>
    {project&&<section className="project-detail"><div className="project-detail-head"><div><span className="eyebrow">Активний проєкт</span><h2>{project.name}</h2></div><div className="project-controls"><div className="color-picks">{colors.map(color=><button key={color} aria-label={`Колір ${color}`} style={{background:color}} onClick={()=>updateProject({color})}/>)}</div><input type="date" aria-label="Дедлайн" value={project.deadline?new Date(project.deadline).toISOString().slice(0,10):""} onChange={event=>updateProject({deadline:event.target.value?new Date(`${event.target.value}T12:00:00`).getTime():null})}/><button onClick={rename}>Перейменувати</button><button onClick={()=>updateProject({archived:!project.archived})}>{project.archived?"Відновити":"Архівувати"}</button></div></div><div className="kanban-board">{columns.map(([status,label])=><div className={`board-column ${status}`} key={status} onDragOver={event=>event.preventDefault()} onDrop={event=>onDrop(event,status)}><h3>{label}<span>{current.filter(task=>(task.status??(task.done?"done":"todo"))===status).length}</span></h3>{current.filter(task=>(task.status??(task.done?"done":"todo"))===status).map(task=><article className="board-task" draggable onDragStart={()=>setDragging(task.id)} onDragEnd={()=>setDragging(null)} key={task.id}><button className="task-grip" aria-label="Перетягнути задачу">⠿</button><span>{task.text}<small>{task.deadline?new Intl.DateTimeFormat("uk-UA",{day:"numeric",month:"short"}).format(task.deadline):"Без дедлайну"}{task.recurrence?` · ${task.recurrence}`:""}</small></span><div className="task-quick-actions"><button type="button" className={task.done?"completed":""} onClick={()=>move(task.id,task.done?"todo":"done")} aria-label={task.done?"Повернути задачу":"Позначити виконаною"}>{task.done?"↶":"✓"}</button><button type="button" onClick={()=>editTask(task)} aria-label="Редагувати задачу">✎</button><button type="button" onClick={()=>duplicateTask(task)} aria-label="Дублювати задачу">⧉</button></div><input className="task-deadline" type="date" aria-label="Дедлайн задачі" value={task.deadline?new Date(task.deadline).toISOString().slice(0,10):""} onChange={event=>updateTask(task.id,{deadline:event.target.value?new Date(`${event.target.value}T12:00:00`).getTime():null})}/><select value={task.recurrence??""} aria-label="Повторення" onChange={event=>updateTask(task.id,{recurrence:event.target.value||null})}><option value="">Разово</option><option value="daily">Щодня</option><option value="weekly">Щотижня</option></select><button className="task-delete" aria-label="Видалити" onClick={()=>removeTask(task.id)}>×</button></article>)}{status==="todo"&&<form onSubmit={addTask}><input value={draft} onChange={event=>setDraft(event.target.value)} placeholder="Нова задача…"/><button type="submit">+</button></form>}</div>)}</div></section>}
  </AppFrame>
}
