import { apiContext, apiError, apiOk, bumpRevision, cleanId, cleanNumber, jsonBody, unauthorized } from "../backend";

export async function GET(request:Request) {
  const context=await apiContext();if(!context)return unauthorized();const url=new URL(request.url),projectId=cleanId(url.searchParams.get("projectId")),from=cleanNumber(url.searchParams.get("from")??0,0,8640000000000000)??0,to=cleanNumber(url.searchParams.get("to")??Date.now(),0,8640000000000000)??Date.now(),limit=cleanNumber(url.searchParams.get("limit")??200,1,1000)??200;let query="SELECT id,project_id AS projectId,started_at AS startedAt,duration_seconds AS durationSeconds FROM focus_sessions WHERE user_id=? AND started_at>=? AND started_at<=?",values:unknown[]=[context.user.userId,from,to];if(projectId){query+=" AND project_id=?";values.push(projectId)}query+=" ORDER BY started_at DESC LIMIT ?";values.push(limit);const rows=await context.db.prepare(query).bind(...values).all();return apiOk(rows.results);
}

export async function POST(request:Request) {
  const context=await apiContext();if(!context)return unauthorized();const body=await jsonBody(request);if(!body)return apiError("INVALID_JSON","Некоректний JSON");const id=cleanId(body.id),projectId=cleanId(body.projectId),startedAt=cleanNumber(body.startedAt,0,Date.now()+86400000),durationSeconds=cleanNumber(body.durationSeconds,1,43200);if(!id||!projectId||startedAt===null||durationSeconds===null)return apiError("VALIDATION_ERROR","Некоректні дані сесії",422);const project=await context.db.prepare("SELECT 1 FROM projects WHERE id=? AND user_id=?").bind(projectId,context.user.userId).first();if(!project)return apiError("PROJECT_NOT_FOUND","Проєкт не знайдено",404);const exists=await context.db.prepare("SELECT user_id AS userId FROM focus_sessions WHERE id=?").bind(id).first<{userId:string}>();if(exists&&exists.userId!==context.user.userId)return apiError("SESSION_EXISTS","Конфлікт id сесії",409);
  if(exists)await context.db.prepare("UPDATE focus_sessions SET project_id=?,started_at=?,duration_seconds=? WHERE id=? AND user_id=?").bind(projectId,startedAt,durationSeconds,id,context.user.userId).run();else await context.db.prepare("INSERT INTO focus_sessions (id,user_id,project_id,started_at,duration_seconds) VALUES (?,?,?,?,?)").bind(id,context.user.userId,projectId,startedAt,durationSeconds).run();const sync=await bumpRevision(context.db,context.user.userId);return apiOk({id,projectId,startedAt,durationSeconds,sync},exists?200:201);
}

export async function DELETE(request:Request) {
  const context=await apiContext();if(!context)return unauthorized();const id=cleanId(new URL(request.url).searchParams.get("id"));if(!id)return apiError("VALIDATION_ERROR","Некоректний id",422);const result=await context.db.prepare("DELETE FROM focus_sessions WHERE id=? AND user_id=?").bind(id,context.user.userId).run();if(!result.meta.changes)return apiError("NOT_FOUND","Сесію не знайдено",404);const sync=await bumpRevision(context.db,context.user.userId);return apiOk({id,deleted:true,sync});
}
